# Generated by Django 5.2 on 2025-04-10 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('popularity', models.FloatField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CountryTrackTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_data.track')),
            ],
        ),
    ]
