# Generated by Django 5.2 on 2025-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='tempo',
            field=models.FloatField(default=120.0),
        ),
        migrations.AlterField(
            model_name='track',
            name='valence',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='CountryTrackTrend',
        ),
    ]
