# Generated by Django 5.2 on 2025-04-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_data', '0002_alter_track_tempo_alter_track_valence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
