# Generated by Django 5.2 on 2025-04-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_data', '0003_track_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='date',
            field=models.CharField(default='-'),
        ),
    ]
