# Generated by Django 5.2 on 2025-04-10 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_data', '0001_initial'),
        ('spotify_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('based_on_track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotify_data.track')),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_data.product')),
            ],
        ),
    ]
